-- Sentinel local development seed
-- Deterministic sample records for a usable inbox after `npm run db:reset`.

delete from public.calls_log where source = 'local_seed';
delete from public.leads where source = 'local_seed';
delete from public.contacts where source = 'local_seed';
delete from public.properties where apn like 'LOCAL-SEED-%';

insert into public.properties (
  id,
  apn,
  county,
  address,
  city,
  state,
  zip,
  owner_name,
  owner_phone,
  owner_email,
  estimated_value,
  equity_percent,
  bedrooms,
  bathrooms,
  sqft,
  year_built,
  lot_size,
  property_type,
  owner_flags,
  notes
)
values
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
    'LOCAL-SEED-001',
    'Spokane',
    '6030 N Smith St',
    'Spokane',
    'WA',
    '99208',
    'Barrington Kip',
    '+15095550101',
    'kip@example.com',
    336998,
    47.50,
    5,
    1.0,
    1976,
    1958,
    7200,
    'Single Family',
    jsonb_build_object(
      'source_channel', 'local_seed',
      'source_vendor', 'Dominion Seed',
      'source_list_name', 'Sentinel Local Demo',
      'niche_tag', 'pre_foreclosure',
      'import_batch_id', 'LOCAL-DEMO-001',
      'skip_trace_status', 'completed'
    ),
    'Local demo property for skip trace and callback testing.'
  ),
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2',
    'LOCAL-SEED-002',
    'Spokane',
    '412 W Kiernan Ave',
    'Spokane',
    'WA',
    '99205',
    'Graser Erin L',
    '+15095550102',
    'erin@example.com',
    289000,
    39.20,
    3,
    2.0,
    1440,
    1979,
    6400,
    'Single Family',
    jsonb_build_object(
      'source_channel', 'local_seed',
      'source_vendor', 'Dominion Seed',
      'source_list_name', 'Sentinel Local Demo',
      'niche_tag', 'absentee',
      'import_batch_id', 'LOCAL-DEMO-001'
    ),
    'Unclaimed lead to exercise inbox triage.'
  ),
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3',
    'LOCAL-SEED-003',
    'Kootenai',
    '1188 E Best Ave',
    'Coeur d''Alene',
    'ID',
    '83814',
    'Bondurant Michael',
    '+12085550103',
    'michael@example.com',
    412500,
    62.10,
    4,
    2.5,
    1830,
    1991,
    9100,
    'Single Family',
    jsonb_build_object(
      'source_channel', 'local_seed',
      'source_vendor', 'Dominion Seed',
      'source_list_name', 'Sentinel Local Demo',
      'niche_tag', 'vacant',
      'import_batch_id', 'LOCAL-DEMO-001'
    ),
    'Negotiation-stage demo file.'
  ),
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4',
    'LOCAL-SEED-004',
    'Spokane',
    '9211 S Regal St',
    'Spokane',
    'WA',
    '99223',
    'Donahue Melissa',
    '+15095550104',
    'melissa@example.com',
    455000,
    31.00,
    4,
    3.0,
    2210,
    2004,
    8200,
    'Single Family',
    jsonb_build_object(
      'source_channel', 'local_seed',
      'source_vendor', 'Dominion Seed',
      'source_list_name', 'Sentinel Local Demo',
      'niche_tag', 'probate',
      'import_batch_id', 'LOCAL-DEMO-001'
    ),
    'Disposition-stage demo file for follow-up and offer views.'
  )
on conflict (id) do update set
  owner_phone = excluded.owner_phone,
  owner_email = excluded.owner_email,
  estimated_value = excluded.estimated_value,
  equity_percent = excluded.equity_percent,
  bedrooms = excluded.bedrooms,
  bathrooms = excluded.bathrooms,
  sqft = excluded.sqft,
  year_built = excluded.year_built,
  lot_size = excluded.lot_size,
  property_type = excluded.property_type,
  owner_flags = excluded.owner_flags,
  notes = excluded.notes;

insert into public.contacts (
  id,
  first_name,
  last_name,
  phone,
  email,
  address,
  source,
  notes
)
values
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1',
    'Kip',
    'Barrington',
    '+15095550101',
    'kip@example.com',
    '6030 N Smith St, Spokane, WA 99208',
    'local_seed',
    'Local seed contact'
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2',
    'Erin',
    'Graser',
    '+15095550102',
    'erin@example.com',
    '412 W Kiernan Ave, Spokane, WA 99205',
    'local_seed',
    'Local seed contact'
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3',
    'Michael',
    'Bondurant',
    '+12085550103',
    'michael@example.com',
    '1188 E Best Ave, Coeur d''Alene, ID 83814',
    'local_seed',
    'Local seed contact'
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4',
    'Melissa',
    'Donahue',
    '+15095550104',
    'melissa@example.com',
    '9211 S Regal St, Spokane, WA 99223',
    'local_seed',
    'Local seed contact'
  )
on conflict (id) do update set
  phone = excluded.phone,
  email = excluded.email,
  address = excluded.address,
  notes = excluded.notes;

insert into public.leads (
  id,
  property_id,
  contact_id,
  status,
  assigned_to,
  priority,
  source,
  promoted_at,
  last_contact_at,
  next_follow_up_at,
  next_call_scheduled_at,
  disposition_code,
  notes,
  tags,
  call_sequence_step,
  total_calls,
  live_answers,
  voicemails_left,
  motivation_level,
  seller_timeline,
  condition_level,
  decision_maker_confirmed,
  price_expectation,
  qualification_route,
  occupancy_score,
  equity_flexibility_score,
  qualification_score_total,
  opportunity_score,
  contactability_score,
  confidence_score,
  seller_situation_summary_short,
  recommended_call_angle,
  top_fact_1,
  top_fact_2,
  top_fact_3,
  market,
  dial_queue_active,
  skip_trace_status
)
values
  (
    '11111111-1111-1111-1111-111111111111',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1',
    'lead',
    null,
    92,
    'local_seed',
    now() - interval '7 days',
    now() - interval '2 days',
    now() - interval '1 day',
    now() - interval '1 day',
    'callback_scheduled',
    'Ask about motivation, decision-maker, and timeline.',
    array['pre_foreclosure', 'callback'],
    1,
    3,
    1,
    1,
    8,
    '30_days',
    5,
    true,
    250000,
    'follow_up',
    4,
    4,
    24,
    81,
    78,
    72,
    'Seller is six days overdue on a callback and may accept a fast close.',
    'Lead with overdue callback and pre-foreclosure urgency.',
    'Owner previously answered live.',
    'Pre-foreclosure list import.',
    'No saved offer yet.',
    'spokane',
    true,
    'completed'
  ),
  (
    '22222222-2222-2222-2222-222222222222',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2',
    'lead',
    null,
    74,
    'local_seed',
    now() - interval '3 days',
    null,
    now() + interval '4 hours',
    now() + interval '4 hours',
    null,
    'Fresh unclaimed absentee lead.',
    array['absentee'],
    1,
    0,
    0,
    0,
    6,
    'flexible',
    4,
    false,
    null,
    null,
    3,
    3,
    18,
    67,
    60,
    58,
    'Needs first outreach.',
    'Open with absentee ownership pain points.',
    'No call attempts yet.',
    'Unclaimed inbox sample.',
    'Good for first-touch testing.',
    'spokane',
    true,
    'not_started'
  ),
  (
    '33333333-3333-3333-3333-333333333333',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3',
    'negotiation',
    null,
    83,
    'local_seed',
    now() - interval '9 days',
    now() - interval '1 day',
    now() + interval '1 day',
    now() + interval '1 day',
    'warm',
    'Negotiation sample with active conversation.',
    array['vacant', 'warm'],
    3,
    5,
    2,
    1,
    7,
    '60_days',
    6,
    true,
    305000,
    'offer_ready',
    4,
    5,
    28,
    79,
    75,
    76,
    'Open to terms if certainty is high.',
    'Lead with flexibility and equity.',
    'Vacant property.',
    'Negotiation phase sample.',
    'Kootenai market sample.',
    'kootenai',
    false,
    'completed'
  ),
  (
    '44444444-4444-4444-4444-444444444444',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4',
    'disposition',
    null,
    65,
    'local_seed',
    now() - interval '14 days',
    now() - interval '3 days',
    now() + interval '2 days',
    now() + interval '2 days',
    'appointment_set',
    'Disposition sample for downstream workflow checks.',
    array['probate', 'appointment'],
    4,
    6,
    2,
    2,
    5,
    'flexible',
    5,
    true,
    338000,
    'offer_ready',
    3,
    3,
    21,
    70,
    62,
    64,
    'Seller wants a clean process more than top dollar.',
    'Lead with simplicity and certainty.',
    'Probate context.',
    'Disposition stage sample.',
    'Ready for offer-prep UI.',
    'spokane',
    false,
    'completed'
  )
on conflict (id) do update set
  property_id = excluded.property_id,
  contact_id = excluded.contact_id,
  status = excluded.status,
  priority = excluded.priority,
  source = excluded.source,
  promoted_at = excluded.promoted_at,
  last_contact_at = excluded.last_contact_at,
  next_follow_up_at = excluded.next_follow_up_at,
  next_call_scheduled_at = excluded.next_call_scheduled_at,
  disposition_code = excluded.disposition_code,
  notes = excluded.notes,
  tags = excluded.tags,
  call_sequence_step = excluded.call_sequence_step,
  total_calls = excluded.total_calls,
  live_answers = excluded.live_answers,
  voicemails_left = excluded.voicemails_left,
  motivation_level = excluded.motivation_level,
  seller_timeline = excluded.seller_timeline,
  condition_level = excluded.condition_level,
  decision_maker_confirmed = excluded.decision_maker_confirmed,
  price_expectation = excluded.price_expectation,
  qualification_route = excluded.qualification_route,
  occupancy_score = excluded.occupancy_score,
  equity_flexibility_score = excluded.equity_flexibility_score,
  qualification_score_total = excluded.qualification_score_total,
  opportunity_score = excluded.opportunity_score,
  contactability_score = excluded.contactability_score,
  confidence_score = excluded.confidence_score,
  seller_situation_summary_short = excluded.seller_situation_summary_short,
  recommended_call_angle = excluded.recommended_call_angle,
  top_fact_1 = excluded.top_fact_1,
  top_fact_2 = excluded.top_fact_2,
  top_fact_3 = excluded.top_fact_3,
  market = excluded.market,
  dial_queue_active = excluded.dial_queue_active,
  skip_trace_status = excluded.skip_trace_status,
  assigned_to = null;

insert into public.calls_log (
  id,
  lead_id,
  property_id,
  user_id,
  phone_dialed,
  disposition,
  duration_sec,
  notes,
  started_at,
  ended_at,
  source
)
values
  (
    'cccccccc-cccc-cccc-cccc-ccccccccccc1',
    '11111111-1111-1111-1111-111111111111',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
    '00000000-0000-0000-0000-000000000001',
    '+15095550101',
    'callback_scheduled',
    211,
    'Seller asked for a callback after talking with family.',
    now() - interval '2 days',
    now() - interval '2 days' + interval '211 seconds',
    'local_seed'
  )
on conflict (id) do update set
  disposition = excluded.disposition,
  duration_sec = excluded.duration_sec,
  notes = excluded.notes,
  started_at = excluded.started_at,
  ended_at = excluded.ended_at;
