import { describe, expect, it } from "vitest";
import { buildTinaReviewDeliveryReport } from "@/tina/lib/review-delivery";
import { createDefaultTinaWorkspaceDraft } from "@/tina/lib/workspace-draft";

describe("buildTinaReviewDeliveryReport", () => {
  it("can mark a strong 1120-S intake packet as ready to send for CPA review", () => {
    const baseDraft = createDefaultTinaWorkspaceDraft();
    const draft = {
      ...baseDraft,
      profile: {
        ...baseDraft.profile,
        businessName: "North Ridge Home Services LLC",
        taxYear: "2025",
        entityType: "s_corp" as const,
        hasPayroll: true,
        naicsCode: "238220",
      },
      priorReturnDocumentId: "prior-doc",
      documents: [
        {
          id: "prior-doc",
          name: "prior-return.csv",
          size: 1300,
          mimeType: "text/csv",
          storagePath: "tina/prior-return.csv",
          category: "prior_return" as const,
          requestId: "prior-return",
          requestLabel: "Prior-year filed return",
          uploadedAt: "2026-04-08T08:00:00.000Z",
        },
        {
          id: "pnl-doc",
          name: "pnl.csv",
          size: 1200,
          mimeType: "text/csv",
          storagePath: "tina/pnl.csv",
          category: "supporting_document" as const,
          requestId: "profit-loss",
          requestLabel: "Full-year profit and loss",
          uploadedAt: "2026-04-08T08:01:00.000Z",
        },
        {
          id: "gl-doc",
          name: "gl.csv",
          size: 1200,
          mimeType: "text/csv",
          storagePath: "tina/gl.csv",
          category: "supporting_document" as const,
          requestId: "general-ledger",
          requestLabel: "General ledger export",
          uploadedAt: "2026-04-08T08:02:00.000Z",
        },
        {
          id: "bank-doc",
          name: "bank.csv",
          size: 1100,
          mimeType: "text/csv",
          storagePath: "tina/bank.csv",
          category: "supporting_document" as const,
          requestId: "bank-support",
          requestLabel: "Business bank statements",
          uploadedAt: "2026-04-08T08:03:00.000Z",
        },
        {
          id: "payroll-doc",
          name: "payroll.csv",
          size: 1100,
          mimeType: "text/csv",
          storagePath: "tina/payroll.csv",
          category: "supporting_document" as const,
          requestId: "payroll",
          requestLabel: "Payroll reports and W-2 support",
          uploadedAt: "2026-04-08T08:04:00.000Z",
        },
        {
          id: "balance-doc",
          name: "balance-sheet.csv",
          size: 900,
          mimeType: "text/csv",
          storagePath: "tina/balance-sheet.csv",
          category: "supporting_document" as const,
          requestId: "balance-sheet",
          requestLabel: "Year-end balance sheet",
          uploadedAt: "2026-04-08T08:04:30.000Z",
        },
        {
          id: "card-doc",
          name: "credit-card.csv",
          size: 900,
          mimeType: "text/csv",
          storagePath: "tina/credit-card.csv",
          category: "supporting_document" as const,
          requestId: "credit-card-support",
          requestLabel: "Business credit card statements",
          uploadedAt: "2026-04-08T08:04:45.000Z",
        },
        {
          id: "notes-doc",
          name: "unusual-items.csv",
          size: 700,
          mimeType: "text/csv",
          storagePath: "tina/unusual-items.csv",
          category: "supporting_document" as const,
          requestId: "unusual-items",
          requestLabel: "Notes about unusual items",
          uploadedAt: "2026-04-08T08:05:00.000Z",
        },
        {
          id: "tb-doc",
          name: "trial-balance.csv",
          size: 900,
          mimeType: "text/csv",
          storagePath: "tina/trial-balance.csv",
          category: "supporting_document" as const,
          requestId: "trial-balance",
          requestLabel: "Year-end trial balance",
          uploadedAt: "2026-04-08T08:05:15.000Z",
        },
        {
          id: "entity-doc",
          name: "entity-docs.pdf",
          size: 900,
          mimeType: "application/pdf",
          storagePath: "tina/entity-docs.pdf",
          category: "supporting_document" as const,
          requestId: "entity-docs",
          requestLabel: "Entity and ownership documents",
          uploadedAt: "2026-04-08T08:05:30.000Z",
        },
        {
          id: "loan-doc",
          name: "loan-support.csv",
          size: 900,
          mimeType: "text/csv",
          storagePath: "tina/loan-support.csv",
          category: "supporting_document" as const,
          requestId: "loan-support",
          requestLabel: "Loan statements and debt support",
          uploadedAt: "2026-04-08T08:05:45.000Z",
        },
        {
          id: "asset-doc",
          name: "fixed-assets.csv",
          size: 900,
          mimeType: "text/csv",
          storagePath: "tina/fixed-assets.csv",
          category: "supporting_document" as const,
          requestId: "assets",
          requestLabel: "Fixed asset and depreciation support",
          uploadedAt: "2026-04-08T08:05:50.000Z",
        },
      ],
      documentReadings: [
        {
          documentId: "prior-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 12,
          headers: ["Form", "Amount"],
          sheetNames: ["Prior Return"],
          lastReadAt: "2026-04-08T08:05:00.000Z",
        },
        {
          documentId: "pnl-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 12,
          headers: ["Account", "Amount"],
          sheetNames: ["P&L"],
          lastReadAt: "2026-04-08T08:05:30.000Z",
        },
        {
          documentId: "gl-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 40,
          headers: ["Date", "Account", "Debit", "Credit"],
          sheetNames: ["GL"],
          lastReadAt: "2026-04-08T08:06:00.000Z",
        },
        {
          documentId: "bank-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 12,
          headers: ["Month", "Deposits", "Withdrawals"],
          sheetNames: ["Bank"],
          lastReadAt: "2026-04-08T08:06:30.000Z",
        },
        {
          documentId: "payroll-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 12,
          headers: ["Employee", "Wages"],
          sheetNames: ["Payroll"],
          lastReadAt: "2026-04-08T08:07:00.000Z",
        },
        {
          documentId: "balance-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 8,
          headers: ["Account", "Amount"],
          sheetNames: ["Balance Sheet"],
          lastReadAt: "2026-04-08T08:07:05.000Z",
        },
        {
          documentId: "card-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 12,
          headers: ["Date", "Amount"],
          sheetNames: ["Credit Card"],
          lastReadAt: "2026-04-08T08:07:10.000Z",
        },
        {
          documentId: "notes-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 4,
          headers: ["Note", "Detail"],
          sheetNames: ["Notes"],
          lastReadAt: "2026-04-08T08:07:15.000Z",
        },
        {
          documentId: "tb-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 16,
          headers: ["Account", "Debit", "Credit"],
          sheetNames: ["Trial Balance"],
          lastReadAt: "2026-04-08T08:07:20.000Z",
        },
        {
          documentId: "entity-doc",
          status: "complete" as const,
          kind: "pdf" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          pageCount: 3,
          lastReadAt: "2026-04-08T08:07:25.000Z",
        },
        {
          documentId: "loan-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 12,
          headers: ["Month", "Interest", "Principal"],
          sheetNames: ["Loans"],
          lastReadAt: "2026-04-08T08:07:30.000Z",
        },
        {
          documentId: "asset-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 10,
          headers: ["Asset", "Placed In Service", "Cost"],
          sheetNames: ["Assets"],
          lastReadAt: "2026-04-08T08:07:35.000Z",
        },
      ],
      sourceFacts: [
        {
          id: "return-type-hint-1",
          sourceDocumentId: "prior-doc",
          label: "Return type hint",
          value: "1120-S",
          confidence: "high" as const,
          capturedAt: "2026-04-08T08:07:30.000Z",
        },
        {
          id: "ownership-clue-1",
          sourceDocumentId: "entity-doc",
          label: "Ownership percentage clue",
          value: "100%",
          confidence: "high" as const,
          capturedAt: "2026-04-08T08:07:40.000Z",
        },
        {
          id: "carryover-clue-1",
          sourceDocumentId: "prior-doc",
          label: "Carryover amount clue",
          value: "$12,000",
          confidence: "medium" as const,
          capturedAt: "2026-04-08T08:07:50.000Z",
        },
        {
          id: "election-clue-1",
          sourceDocumentId: "entity-doc",
          label: "Election detail clue",
          value: "S election accepted",
          confidence: "medium" as const,
          capturedAt: "2026-04-08T08:08:00.000Z",
        },
        {
          id: "depr-clue-1",
          sourceDocumentId: "loan-doc",
          label: "Depreciation clue",
          value: "Equipment depreciation support carried forward",
          confidence: "medium" as const,
          capturedAt: "2026-04-08T08:08:10.000Z",
        },
      ],
      reviewerOutcomeMemory: {
        updatedAt: "2026-04-08T08:08:00.000Z",
        summary: "Thin but clean history.",
        nextStep: "Keep measuring.",
        scorecard: {
          totalOutcomes: 2,
          acceptedCount: 2,
          revisedCount: 0,
          rejectedCount: 0,
          acceptanceScore: 100,
          trustLevel: "developing" as const,
          nextStep: "Keep measuring.",
          patterns: [],
        },
        overrides: [],
        outcomes: [],
      },
    };

    const report = buildTinaReviewDeliveryReport(draft);

    expect(report.status).toBe("ready_to_send");
    expect(
      report.checks.find((check) => check.id === "entity_return_intake_contract")?.status
    ).toBe("ready");
    expect(report.checks.find((check) => check.id === "s_corp_review_spine")?.status).toBe(
      "ready"
    );
    expect(report.checks.find((check) => check.id === "s_corp_prep_spine")?.status).toBe(
      "ready"
    );
  });

  it("blocks sending when package readiness is still blocked", () => {
    const draft = createDefaultTinaWorkspaceDraft();

    const report = buildTinaReviewDeliveryReport(draft);

    expect(report.status).toBe("blocked");
    expect(report.checks.find((check) => check.id === "package_readiness")?.status).toBe(
      "blocked"
    );
  });

  it("marks a strong supported packet as ready to send for CPA review", () => {
    const baseDraft = createDefaultTinaWorkspaceDraft();
    const draft = {
      ...baseDraft,
      profile: {
        ...baseDraft.profile,
        businessName: "Ready Review LLC",
        entityType: "single_member_llc" as const,
      },
      documents: [
        {
          id: "prior-doc",
          name: "2024-return.pdf",
          size: 1300,
          mimeType: "application/pdf",
          storagePath: "tina/2024-return.pdf",
          category: "prior_return" as const,
          requestId: "prior-return",
          requestLabel: "Last year's return",
          uploadedAt: "2026-04-07T07:59:00.000Z",
        },
        {
          id: "doc-1",
          name: "qb-export.csv",
          size: 1200,
          mimeType: "text/csv",
          storagePath: "tina/qb-export.csv",
          category: "supporting_document" as const,
          requestId: "quickbooks",
          requestLabel: "QuickBooks export",
          uploadedAt: "2026-04-07T08:00:00.000Z",
        },
        {
          id: "bank-doc",
          name: "bank-export.csv",
          size: 1100,
          mimeType: "text/csv",
          storagePath: "tina/bank-export.csv",
          category: "supporting_document" as const,
          requestId: "bank-support",
          requestLabel: "Bank support",
          uploadedAt: "2026-04-07T08:00:30.000Z",
        },
      ],
      priorReturnDocumentId: "prior-doc",
      documentReadings: [
        {
          documentId: "doc-1",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 12,
          headers: ["Date", "Amount"],
          sheetNames: ["Sheet1"],
          lastReadAt: "2026-04-07T08:01:00.000Z",
        },
        {
          documentId: "bank-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 10,
          headers: ["Date", "Amount"],
          sheetNames: ["Sheet1"],
          lastReadAt: "2026-04-07T08:01:30.000Z",
        },
      ],
      sourceFacts: [
        {
          id: "group-1",
          sourceDocumentId: "doc-1",
          label: "Transaction group clue",
          value: "Client receipts (inflow): 4 rows, total $18,000.00, dates Apr 1, 2026 to Apr 30, 2026",
          confidence: "medium" as const,
          capturedAt: "2026-04-07T08:02:00.000Z",
        },
      ],
      bookTieOut: {
        ...baseDraft.bookTieOut,
        status: "complete" as const,
        entries: [
          {
            id: "book-doc-1",
            documentId: "doc-1",
            label: "QuickBooks export",
            status: "ready" as const,
            moneyIn: 18000,
            moneyOut: 0,
            net: 18000,
            dateCoverage: "2026-04-01 through 2026-04-30",
            sourceFactIds: ["group-1"],
            issueIds: [],
          },
        ],
        variances: [],
      },
      taxAdjustments: {
        ...baseDraft.taxAdjustments,
        status: "complete" as const,
        summary: "Tax adjustments ready.",
        adjustments: [
          {
            id: "adj-1",
            kind: "carryforward_line" as const,
            status: "approved" as const,
            risk: "low" as const,
            requiresAuthority: false,
            title: "Carry receipts",
            summary: "Approved.",
            suggestedTreatment: "Carry to Schedule C line 1.",
            whyItMatters: "Traceability.",
            amount: 18000,
            authorityWorkIdeaIds: [],
            aiCleanupLineIds: ["ai-1"],
            sourceDocumentIds: ["doc-1"],
            sourceFactIds: [],
            reviewerNotes: "Approved for CPA packet.",
          },
        ],
      },
      reviewerFinal: {
        ...baseDraft.reviewerFinal,
        lastRunAt: "2026-04-07T08:05:00.000Z",
        status: "complete" as const,
        summary: "Reviewer-final ready.",
        lines: [
          {
            id: "rf-1",
            kind: "income" as const,
            layer: "reviewer_final" as const,
            label: "Gross receipts candidate",
            amount: 18000,
            status: "ready" as const,
            summary: "Ready.",
            sourceDocumentIds: ["doc-1"],
            sourceFactIds: [],
            issueIds: [],
            derivedFromLineIds: ["ai-1"],
            cleanupSuggestionIds: [],
            taxAdjustmentIds: ["adj-1"],
          },
        ],
      },
      packageReadiness: {
        ...baseDraft.packageReadiness,
        lastRunAt: "2026-04-07T08:06:00.000Z",
        status: "complete" as const,
        level: "ready_for_cpa" as const,
        summary: "Tina does not see anything blocking a CPA-ready package right now.",
      },
      scheduleCDraft: {
        ...baseDraft.scheduleCDraft,
        lastRunAt: "2026-04-07T08:05:30.000Z",
        status: "complete" as const,
        summary: "Schedule C ready.",
        fields: [
          {
            id: "line-1",
            lineNumber: "Line 1",
            label: "Gross receipts or sales",
            amount: 18000,
            status: "ready" as const,
            summary: "Supported.",
            reviewerFinalLineIds: ["rf-1"],
            taxAdjustmentIds: ["adj-1"],
            sourceDocumentIds: ["doc-1"],
          },
        ],
        notes: [],
      },
      taxPositionMemory: {
        ...baseDraft.taxPositionMemory,
        status: "complete" as const,
        summary: "Tax positions are current.",
        records: [
          {
            id: "position-1",
            adjustmentId: "adj-1",
            title: "Carry receipts",
            status: "ready" as const,
            confidence: "high" as const,
            summary: "Supported.",
            treatmentSummary: "Carry to Schedule C line 1.",
            reviewerGuidance: "Strong reviewer history.",
            authorityWorkIdeaIds: [],
            sourceDocumentIds: ["doc-1"],
            sourceFactIds: [],
            reviewerOutcomeIds: [],
            reviewerOverrideIds: [],
            updatedAt: "2026-04-07T08:10:00.000Z",
          },
        ],
      },
      reviewerOutcomeMemory: {
        updatedAt: "2026-04-07T08:10:00.000Z",
        summary: "Strong outcome history.",
        nextStep: "Keep measuring.",
        scorecard: {
          totalOutcomes: 4,
          acceptedCount: 4,
          revisedCount: 0,
          rejectedCount: 0,
          acceptanceScore: 100,
          trustLevel: "strong" as const,
          nextStep: "Keep measuring.",
          patterns: [],
        },
        overrides: [],
        outcomes: [
          {
            id: "outcome-1",
            title: "Accepted",
            phase: "package" as const,
            verdict: "accepted" as const,
            targetType: "reviewer_final_line" as const,
            targetId: "rf-1",
            summary: "Accepted.",
            lessons: [],
            caseTags: ["clean_books", "schedule_c"] as const,
            overrideIds: [],
            decidedAt: "2026-04-06T08:10:00.000Z",
            decidedBy: "reviewer-1",
          },
          {
            id: "outcome-2",
            title: "Accepted",
            phase: "package" as const,
            verdict: "accepted" as const,
            targetType: "reviewer_final_line" as const,
            targetId: "rf-2",
            summary: "Accepted.",
            lessons: [],
            caseTags: ["clean_books", "schedule_c"] as const,
            overrideIds: [],
            decidedAt: "2026-04-05T08:10:00.000Z",
            decidedBy: "reviewer-1",
          },
          {
            id: "outcome-3",
            title: "Accepted",
            phase: "tax_review" as const,
            verdict: "accepted" as const,
            targetType: "tax_adjustment" as const,
            targetId: "adj-1",
            summary: "Accepted.",
            lessons: [],
            caseTags: ["clean_books", "schedule_c"] as const,
            overrideIds: [],
            decidedAt: "2026-04-04T08:10:00.000Z",
            decidedBy: "reviewer-1",
          },
          {
            id: "outcome-4",
            title: "Accepted",
            phase: "tax_review" as const,
            verdict: "accepted" as const,
            targetType: "tax_adjustment" as const,
            targetId: "adj-2",
            summary: "Accepted.",
            lessons: [],
            caseTags: ["clean_books", "schedule_c"] as const,
            overrideIds: [],
            decidedAt: "2026-04-03T08:10:00.000Z",
            decidedBy: "reviewer-1",
          },
        ],
      },
    };

    const report = buildTinaReviewDeliveryReport(draft);

    expect(report.checks.map((check) => `${check.id}:${check.status}`)).toEqual([
      "package_readiness:ready",
      "cpa_packet:ready",
      "tax_positions:ready",
      "current_file_acceptance:ready",
      "current_file_reviewer_reality:ready",
      "final_package_quality:ready",
      "transaction_lineage:ready",
      "review_mode:ready",
      "mef_handoff:ready",
      "continuity_and_depreciation:ready",
    ]);
    expect(report.status).toBe("ready_to_send");
    expect(report.checks.every((check) => check.status === "ready")).toBe(true);
  });

  it("keeps delivery in needs-review mode when continuity or depreciation review is still open", () => {
    const baseDraft = createDefaultTinaWorkspaceDraft();
    const draft = {
      ...baseDraft,
      profile: {
        ...baseDraft.profile,
        businessName: "Carryover Review LLC",
        entityType: "single_member_llc" as const,
      },
      documents: [
        {
          id: "prior-doc",
          name: "2024-return.pdf",
          size: 1300,
          mimeType: "application/pdf",
          storagePath: "tina/2024-return.pdf",
          category: "prior_return" as const,
          requestId: "prior-return",
          requestLabel: "Last year's return",
          uploadedAt: "2026-04-07T07:59:00.000Z",
        },
        {
          id: "doc-1",
          name: "qb-export.csv",
          size: 1200,
          mimeType: "text/csv",
          storagePath: "tina/qb-export.csv",
          category: "supporting_document" as const,
          requestId: "quickbooks",
          requestLabel: "QuickBooks export",
          uploadedAt: "2026-04-07T08:00:00.000Z",
        },
        {
          id: "bank-doc",
          name: "bank-export.csv",
          size: 1100,
          mimeType: "text/csv",
          storagePath: "tina/bank-export.csv",
          category: "supporting_document" as const,
          requestId: "bank-support",
          requestLabel: "Bank support",
          uploadedAt: "2026-04-07T08:00:30.000Z",
        },
      ],
      priorReturnDocumentId: "prior-doc",
      documentReadings: [
        {
          documentId: "doc-1",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 12,
          headers: ["Date", "Amount"],
          sheetNames: ["Sheet1"],
          lastReadAt: "2026-04-07T08:01:00.000Z",
        },
        {
          documentId: "bank-doc",
          status: "complete" as const,
          kind: "spreadsheet" as const,
          summary: "Read.",
          nextStep: "Done.",
          facts: [],
          detailLines: [],
          rowCount: 10,
          headers: ["Date", "Amount"],
          sheetNames: ["Sheet1"],
          lastReadAt: "2026-04-07T08:01:30.000Z",
        },
      ],
      reviewerFinal: {
        ...baseDraft.reviewerFinal,
        status: "complete" as const,
      },
      scheduleCDraft: {
        ...baseDraft.scheduleCDraft,
        status: "complete" as const,
      },
      packageReadiness: {
        ...baseDraft.packageReadiness,
        status: "complete" as const,
        level: "needs_review" as const,
        items: [
          {
            id: "continuity-review-missing",
            title: "Carryover continuity is still not governed in the package",
            summary: "Needs continuity review",
            severity: "needs_attention" as const,
            relatedFieldIds: [],
            relatedNoteIds: [],
            relatedReviewItemIds: [],
            sourceDocumentIds: ["doc-prior"],
          },
        ],
      },
      sourceFacts: [
        {
          id: "return-type-hint-1",
          sourceDocumentId: "prior-doc",
          label: "Return type hint",
          value: "Schedule C / 1040",
          confidence: "high" as const,
          capturedAt: "2026-04-07T08:00:00.000Z",
        },
        {
          id: "carryover-1",
          sourceDocumentId: "prior-doc",
          label: "Carryover amount clue",
          value: "$1,250.00",
          confidence: "medium" as const,
          capturedAt: "2026-04-07T08:00:00.000Z",
        },
      ],
      taxAdjustments: {
        ...baseDraft.taxAdjustments,
        status: "complete" as const,
        adjustments: [],
      },
      taxPositionMemory: {
        ...baseDraft.taxPositionMemory,
        status: "complete" as const,
        records: [],
      },
      reviewerOutcomeMemory: {
        ...baseDraft.reviewerOutcomeMemory,
        scorecard: {
          ...baseDraft.reviewerOutcomeMemory.scorecard,
          trustLevel: "mixed" as const,
        },
      },
    };

    const report = buildTinaReviewDeliveryReport(draft);
    expect(report.status).toBe("needs_review");
    expect(
      report.checks.find((check) => check.id === "continuity_and_depreciation")?.status
    ).toBe("needs_review");
  });

  it("blocks sending when transaction lineage still shows unresolved specialized activity", () => {
    const baseDraft = createDefaultTinaWorkspaceDraft();
    const draft = {
      ...baseDraft,
      documents: [
        {
          id: "doc-1",
          name: "qb-export.csv",
          size: 1200,
          mimeType: "text/csv",
          storagePath: "tina/qb-export.csv",
          category: "supporting_document" as const,
          requestId: "quickbooks",
          requestLabel: "QuickBooks export",
          uploadedAt: "2026-04-07T08:00:00.000Z",
        },
      ],
      sourceFacts: [
        {
          id: "group-1",
          sourceDocumentId: "doc-1",
          label: "Transaction group clue",
          value:
            "Payroll register (outflow): 3 rows, total ($3,000.00), dates Jan 1, 2025 to Jan 31, 2025",
          confidence: "medium" as const,
          capturedAt: "2026-04-07T08:02:00.000Z",
        },
        {
          id: "lineage-1",
          sourceDocumentId: "doc-1",
          label: "Transaction lineage clue",
          value:
            "Payroll register | 2025-01 (outflow): 3 rows, total ($3,000.00), dates Jan 1, 2025 to Jan 31, 2025",
          confidence: "medium" as const,
          capturedAt: "2026-04-07T08:02:30.000Z",
        },
      ],
      packageReadiness: {
        ...baseDraft.packageReadiness,
        lastRunAt: "2026-04-07T08:06:00.000Z",
        status: "complete" as const,
        level: "ready_for_cpa" as const,
        summary: "Looks ready, but not really.",
      },
      taxAdjustments: {
        ...baseDraft.taxAdjustments,
        status: "complete" as const,
        adjustments: [
          {
            id: "adj-1",
            kind: "carryforward_line" as const,
            status: "approved" as const,
            risk: "low" as const,
            requiresAuthority: false,
            title: "Carry payroll",
            summary: "Approved.",
            suggestedTreatment: "Carry it.",
            whyItMatters: "Traceability.",
            amount: 3000,
            authorityWorkIdeaIds: [],
            aiCleanupLineIds: ["ai-1"],
            sourceDocumentIds: ["doc-1"],
            sourceFactIds: ["group-1", "lineage-1"],
            reviewerNotes: "Approved for packet.",
          },
        ],
      },
      reviewerFinal: {
        ...baseDraft.reviewerFinal,
        status: "complete" as const,
      },
      scheduleCDraft: {
        ...baseDraft.scheduleCDraft,
        status: "complete" as const,
      },
      taxPositionMemory: {
        ...baseDraft.taxPositionMemory,
        status: "complete" as const,
        records: [],
      },
    };

    const report = buildTinaReviewDeliveryReport(draft);

    expect(report.status).toBe("blocked");
    expect(report.checks.find((check) => check.id === "transaction_lineage")?.status).toBe(
      "blocked"
    );
  });
});
