-- Lead Contradiction Flags
--
-- Stores per-lead contradiction findings generated by the contradiction scanner.
-- Each row is one detected inconsistency between CRM fields, dossier data,
-- fact assertions, or operator notes.
--
-- Findings are:
--   - Generated by deterministic checks (never auto-generated by background AI)
--   - Manually triggered by Adam via the scan endpoint
--   - Reviewed and dismissed by Adam: marked real, false_positive, or resolved
--   - Never used to auto-update CRM state or lead stage
--
-- Rollback:
--   DROP TABLE IF EXISTS lead_contradiction_flags;

CREATE TABLE IF NOT EXISTS lead_contradiction_flags (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  lead_id         UUID        NOT NULL REFERENCES leads(id) ON DELETE CASCADE,

  -- Contradiction type — bounded app-enforced allowlist:
  --   "authority_unclear"     — DM confirmed but ownership/heir evidence conflicts
  --   "occupancy_mismatch"    — operator says vacant but evidence says occupied
  --   "lien_vs_clean"         — offer-ready route but lien/financial burden evidence
  --   "condition_vs_offer"    — offer-ready route but condition unknown or very poor
  check_type      TEXT        NOT NULL,

  -- Severity
  severity        TEXT        NOT NULL DEFAULT 'warn',
  -- "warn"  = worth reviewing before making an offer
  -- "flag"  = strong signal, inspect before committing

  -- Human-readable description of the contradiction
  description     TEXT        NOT NULL,

  -- Which data signals are in conflict (for UI "why flagged" links)
  -- JSON array of { source: string, value: string, label: string }
  evidence_a      JSONB,      -- first side of contradiction (e.g. CRM field)
  evidence_b      JSONB,      -- second side of contradiction (e.g. fact assertion)

  -- Optional direct link to an artifact or fact that supports evidence_b
  fact_id         UUID        REFERENCES fact_assertions(id) ON DELETE SET NULL,
  artifact_id     UUID        REFERENCES dossier_artifacts(id) ON DELETE SET NULL,

  -- Review lifecycle
  status          TEXT        NOT NULL DEFAULT 'unreviewed',
  -- "unreviewed"    = just generated, not yet seen by Adam
  -- "real"          = Adam confirmed this is a real contradiction to track
  -- "false_positive" = Adam dismissed as not a real conflict
  -- "resolved"      = contradiction was resolved (e.g. new info confirmed DM)

  review_note     TEXT,       -- operator note when reviewing
  reviewed_by     UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at     TIMESTAMPTZ,

  -- Scan metadata
  scanned_by      UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_lead_contradiction_flags_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER tg_contradiction_flags_updated_at
  BEFORE UPDATE ON lead_contradiction_flags
  FOR EACH ROW EXECUTE FUNCTION update_lead_contradiction_flags_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_contradiction_flags_lead
  ON lead_contradiction_flags (lead_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_contradiction_flags_status
  ON lead_contradiction_flags (status, created_at DESC)
  WHERE status = 'unreviewed';

CREATE INDEX IF NOT EXISTS idx_contradiction_flags_severity
  ON lead_contradiction_flags (severity, created_at DESC);

-- RLS
ALTER TABLE lead_contradiction_flags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_contradiction_flags"
  ON lead_contradiction_flags FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

CREATE POLICY "authenticated_read_contradiction_flags"
  ON lead_contradiction_flags FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "authenticated_insert_contradiction_flags"
  ON lead_contradiction_flags FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "authenticated_update_contradiction_flags"
  ON lead_contradiction_flags FOR UPDATE
  TO authenticated
  USING (true);
