-- Call QA Findings
--
-- Stores per-call QA findings generated by the dialer QA runner.
-- Each finding represents one bounded check result for a specific call.
--
-- Findings are:
--   - Generated by deterministic checks (qual gaps, missing next action, short calls)
--     or AI-assisted notes checks (trust-risk phrasing, weak objection handling)
--   - Always tied to a specific calls_log row (and optionally a session)
--   - Reviewed by Adam: marked valid, invalid, or corrected
--   - Never used to auto-update CRM state or operator records
--
-- Rollback:
--   DROP TABLE IF EXISTS call_qa_findings;

CREATE TABLE IF NOT EXISTS call_qa_findings (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Call linkage
  call_log_id     UUID        NOT NULL REFERENCES calls_log(id) ON DELETE CASCADE,
  lead_id         UUID        REFERENCES leads(id)         ON DELETE SET NULL,
  session_id      UUID        REFERENCES call_sessions(id) ON DELETE SET NULL,

  -- Finding content
  check_type      TEXT        NOT NULL,
  -- Bounded allowlist (app-enforced):
  --   "missing_qual"       — one or more qualification fields still null after a live call
  --   "no_next_action"     — no task created after follow_up / appointment disposition
  --   "unresolved_objection" — open objection tag exists with no resolution
  --   "short_call"         — live-answer call under threshold duration (e.g. < 60s)
  --   "no_notes"           — completed/follow_up with no operator notes
  --   "ai_notes_flag"      — AI review of operator notes surfaced a concern
  --   "trust_risk"         — AI detected potentially trust-risky phrasing in notes

  severity        TEXT        NOT NULL DEFAULT 'warn',
  -- Bounded: "info" | "warn" | "flag"
  --   info  = FYI, no action required
  --   warn  = worth reviewing, may affect follow-up
  --   flag  = strong signal, Adam should inspect

  finding         TEXT        NOT NULL,
  -- Human-readable description of what was found.
  -- For deterministic checks: generated from structured data.
  -- For AI checks: AI-generated text, labeled in UI as "AI-derived".

  -- AI linkage (optional — only when check used AI)
  ai_derived      BOOLEAN     NOT NULL DEFAULT FALSE,
  run_id          UUID,       -- links to dialer_ai_traces.run_id if AI was used

  -- Review state
  status          TEXT        NOT NULL DEFAULT 'pending_review',
  -- Bounded: "pending_review" | "valid" | "invalid" | "corrected"
  correction_note TEXT,       -- operator note when status = corrected or invalid

  -- Authorship
  run_by          UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_by     UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at     TIMESTAMPTZ,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger to keep updated_at current
CREATE OR REPLACE FUNCTION update_call_qa_findings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER tg_call_qa_findings_updated_at
  BEFORE UPDATE ON call_qa_findings
  FOR EACH ROW EXECUTE FUNCTION update_call_qa_findings_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_call_qa_findings_call_log
  ON call_qa_findings (call_log_id);

CREATE INDEX IF NOT EXISTS idx_call_qa_findings_lead
  ON call_qa_findings (lead_id)
  WHERE lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_call_qa_findings_status
  ON call_qa_findings (status, created_at DESC)
  WHERE status = 'pending_review';

CREATE INDEX IF NOT EXISTS idx_call_qa_findings_severity
  ON call_qa_findings (severity, created_at DESC);

-- RLS
ALTER TABLE call_qa_findings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_qa_findings"
  ON call_qa_findings FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

CREATE POLICY "authenticated_read_qa_findings"
  ON call_qa_findings FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "authenticated_insert_qa_findings"
  ON call_qa_findings FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "authenticated_update_qa_findings"
  ON call_qa_findings FOR UPDATE
  TO authenticated
  USING (true);
