
-- ============================================================
-- SAURON V0 — AI CEO Command Brief System
-- Deployed: 2026-04-01
-- Purpose: Unified morning brief across Dominion + WrenchReady
-- Unplug: DROP SCHEMA sauron CASCADE;
-- ============================================================

CREATE SCHEMA IF NOT EXISTS sauron;

-- 1. BUSINESSES — The entities Sauron manages
CREATE TABLE sauron.businesses (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    legal_name      TEXT,
    business_type   TEXT,       -- 'acquisitions', 'service'
    active          BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO sauron.businesses (id, name, legal_name, business_type) VALUES
('dominion', 'Dominion Homes', 'Dominion Homes, LLC', 'acquisitions'),
('wrenchready', 'WrenchReady Mobile', 'WrenchReady Mobile, LLC', 'service');

-- 2. BRIEFS — Daily command briefs generated by Sauron
CREATE TABLE sauron.briefs (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    brief_date      DATE NOT NULL DEFAULT CURRENT_DATE,
    brief_type      TEXT NOT NULL DEFAULT 'daily',  -- daily, weekly, monthly, ad_hoc
    content         TEXT NOT NULL,                   -- The actual brief text
    data_snapshot   JSONB,                           -- Raw data that informed the brief
    action_items    JSONB,                           -- Extracted action items
    delivered_via   TEXT,                             -- 'slack', 'sms', 'email'
    delivered_at    TIMESTAMPTZ,
    acknowledged_at TIMESTAMPTZ,                     -- When Dez opened/responded
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(brief_date, brief_type)
);

-- 3. ACTION_ITEMS — Things Sauron surfaced that need attention
CREATE TABLE sauron.action_items (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    business_id     TEXT REFERENCES sauron.businesses(id),
    brief_id        BIGINT REFERENCES sauron.briefs(id),
    priority        TEXT DEFAULT 'normal',  -- critical, high, normal, low
    zone            INTEGER DEFAULT 1,      -- 1=auto, 2=log, 3=needs_approval, 4=human_only
    title           TEXT NOT NULL,
    description     TEXT,
    status          TEXT DEFAULT 'open',     -- open, approved, vetoed, done, expired
    due_by          TIMESTAMPTZ,
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_action_items_status ON sauron.action_items (status) WHERE status = 'open';
CREATE INDEX idx_action_items_business ON sauron.action_items (business_id);

-- 4. METRICS_LOG — Daily KPI snapshots for trend tracking
CREATE TABLE sauron.metrics_log (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    business_id     TEXT REFERENCES sauron.businesses(id),
    metric_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    metric_name     TEXT NOT NULL,
    metric_value    NUMERIC,
    metric_unit     TEXT,           -- 'dollars', 'count', 'percent', 'seconds'
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(business_id, metric_date, metric_name)
);

CREATE INDEX idx_metrics_business_date ON sauron.metrics_log (business_id, metric_date DESC);

-- 5. DATA_SOURCES — What Sauron checks each morning
CREATE TABLE sauron.data_sources (
    id              TEXT PRIMARY KEY,
    business_id     TEXT REFERENCES sauron.businesses(id),
    source_name     TEXT NOT NULL,
    source_type     TEXT NOT NULL,     -- 'supabase', 'google_ads', 'jobber', 'manual'
    query_config    JSONB,             -- How to query this source
    check_frequency TEXT DEFAULT 'daily',
    active          BOOLEAN DEFAULT TRUE,
    last_checked    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO sauron.data_sources (id, business_id, source_name, source_type, query_config) VALUES
('tax_scout', 'dominion', 'Tax Scout - Delinquent Properties', 'supabase', 
 '{"schema": "tax_scout", "view": "delinquent_leads", "key_metrics": ["total_count", "new_since_last", "top_10_by_score"]}'::jsonb),
('dominion_leads', 'dominion', 'Sentinel Lead Pipeline', 'supabase',
 '{"schema": "public", "tables": ["leads"], "key_metrics": ["new_leads_24h", "pipeline_value", "stale_leads"]}'::jsonb),
('dominion_ads', 'dominion', 'Google Ads - Dominion', 'google_ads',
 '{"account": "dominion", "key_metrics": ["spend_yesterday", "leads_generated", "cost_per_lead"]}'::jsonb),
('wrench_bookings', 'wrenchready', 'WrenchReady Bookings', 'supabase',
 '{"key_metrics": ["bookings_today", "bookings_tomorrow", "pending_invoices"]}'::jsonb),
('wrench_ads', 'wrenchready', 'Google Ads - WrenchReady', 'google_ads',
 '{"account": "wrenchready", "key_metrics": ["spend_yesterday", "bookings_generated", "cost_per_booking"]}'::jsonb);

-- 6. DIRECTIVES — Standing orders from Dez that Sauron follows
CREATE TABLE sauron.directives (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    directive       TEXT NOT NULL,
    priority        INTEGER DEFAULT 5,   -- 1=highest
    active          BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO sauron.directives (directive, priority) VALUES
('Surface tax-delinquent residential properties in Spokane County with 2+ years unpaid', 1),
('Alert me if Google Ads spend exceeds daily budget by more than 20%', 2),
('Flag any WrenchReady booking for today that is unconfirmed', 2),
('Tell me about new motivated seller inquiries immediately', 1),
('Track cost-per-lead trend weekly and flag if it rises more than 15%', 3),
('Never let a hot lead go more than 24 hours without contact', 1),
('Summarize WrenchReady revenue weekly — compare to prior week', 4);

